version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.2.3

jobs:
  execute-cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: Deploy to aws from template
          command: |
            set -x
            aws cloudformation deploy --template cloudformation/service.yml --stack-name sampleStackFromCircleCI

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  circleci-live-demo15-20240817-workflow:
    jobs:
      - execute-cloudformation
